/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#e2e2e2',
        'surface-variant': '#e2e2e2',
        'on-secondary-fixed': '#1a1c1c',
        outline: '#7e7576',
        'on-secondary-fixed-variant': '#454747',
        error: '#ba1a1a',
        tertiary: '#000000',
        'on-primary': '#ffffff',
        primary: '#000000',
        'surface-bright': '#f9f9f9',
        'outline-variant': '#cfc4c5',
        'on-secondary': '#ffffff',
        'surface-dim': '#dadada',
        'on-secondary-container': '#616363',
        'surface-container-high': '#e8e8e8',
        'inverse-primary': '#c6c6c6',
        'surface-container-low': '#f3f3f3',
        'inverse-surface': '#2f3131',
        'secondary-fixed': '#e2e2e2',
        'on-surface-variant': '#4c4546',
        'inverse-on-surface': '#f1f1f1',
        'on-error': '#ffffff',
        secondary: '#5d5f5f',
        'primary-fixed': '#e2e2e2',
        'on-background': '#1a1c1c',
        'secondary-fixed-dim': '#c6c6c7',
        'on-error-container': '#93000a',
        'on-primary-container': '#848484',
        'error-container': '#ffdad6',
        'on-surface': '#1a1c1c',
        background: '#f9f9f9',
        surface: '#f9f9f9',
        'surface-container': '#eeeeee',
        'surface-container-lowest': '#ffffff',
        'primary-container': '#1b1b1b',
        'secondary-container': '#dfe0e0',
      },
      borderRadius: {
        DEFAULT: '0px',
        sm: '0px',
        md: '0px',
        lg: '0px',
        xl: '0px',
        '2xl': '0px',
        full: '9999px',
      },
      fontFamily: {
        'headline-xl': ['Space Grotesk', 'sans-serif'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'label-caps': ['Space Grotesk', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', letterSpacing: '0', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
